# BUNGEE CONFIG

# Configure Mqtt communications section for init plugin

# HTTP web communication urls
url_register: http://www.ecuacraft.net/api/ec/vue/user
url_restore: http://www.ecuacraft.net/api/user/reset

# Mqtt communications
# Mqtt: is a protocol use in IoT (Internet of Things).
mqtt: true
mqtt_server: tcp://142.44.143.2
mqtt_port: 1883
mqtt_user: detzerg
mqtt_password: '@detzerg1995@'

# Local Bungee Server Params
# @server_id, @server_name: can be unique in all network, if @server_autoconfig is false
server_id: 0
server_name: ''
server_description: BungeeCord Description!

# ++++++++++++++++++++++++++++++++++++++++++
# -      S y n c     C o m m a n d s       -
# ++++++++++++++++++++++++++++++++++++++++++

# Perms to use sync commands
# @allow_roles: only to web dashboard admin
allowed_roles:
- Owner
- Admin
- Mod
denied_commands:
- end
- bp
denied_users: []

# Database Storage
use_db: false
host: localhost
database: ecnetwork
user: root
password: ''

# ++++++++++++++++++++++++++++++++++++++++++
# -    R e p o r t    M o d u l e          -
# ++++++++++++++++++++++++++++++++++++++++++

# Messages
report_format_body:
- '&a&l=-=-=-=-=-=-=-=-=-=-=-=-=-='
- ''
- '&e&l      NEW REPORT'
- ''
- '&c&lWho report:'
- '&7{player}'
- '&c&lReported:'
- '&7{victim}'
- ''
- '&6&lReason:'
- '&7{reason}'
- '&6&lServer:'
- '&7{server}'
- ''
report_format_footer: '&a&l=-=-=-=-=-=-=-=-=-=-=-=-=-='
goto: '&9&l&nClick&r &fto review the report'
goto_hover: '&aGo to the server &e>>'