# SPIGOT CONFIG

# Mqtt communications
# Mqtt: is a protocol use in IoT (Internet of Things).
mqtt: true
mqtt_server: tcp://142.44.143.2
mqtt_port: 1883
mqtt_user: detzerg
mqtt_password: '@detzerg1995@'

# Local Spigot Server Params
# @server_id, @server_name: can be unique in all network
server_id: 0
server_name: ''
server_description: Spigot/Bukkit Server

# ++++++++++++++++++++++++++++++++++++++++++
# -      S y n c     C o m m a n d s       -
# ++++++++++++++++++++++++++++++++++++++++++

# Perms to use sync commands
# @allow_roles: only to web dashboard admin
allowed_roles:
- Owner
- Admin
- Mod
denied_commands:
- op
- stop
- reload
denied_users: []

# Database Storage
use_db: false
host: localhost
database: ecnetwork
user: root
password: ''
